"""
===========================
Tests for the category production dataset, primarily for refactoring.
===========================

Dr. Cai Wingfield
---------------------------
Embodied Cognition Lab
Department of Psychology
University of Lancaster
c.wingfield@lancaster.ac.uk
caiwingfield.net
---------------------------
2018
---------------------------
"""
import unittest

from category_production import CategoryProduction


class TestVocabulary(unittest.TestCase):

    def test_multi_word_vocabulary(self):
        cp = CategoryProduction(word_tokenise=None)
        self.assertListEqual(
            cp.multi_word_vocabulary,
            ["1pm", "2pm", "3pm", "4pm", "57", "abrupt", "absinthe", "abstract", "academic", "academic subject",
             "accounting", "aching", "acorn", "acquaintance", "acquaintances", "action", "actor", "actress", "adder",
             "adhd", "adjective", "adventure", "adverb", "aeroplane", "afraid", "afternoon", "aggressive", "aids",
             "air rifle", "alcohol", "alcoholic drink", "algebra", "alien", "almond", "almonds", "aluminium", "amber",
             "ambulance", "american football", "amethyst", "anaconda", "anchor", "angel", "angelfish", "anger", "angry",
             "animal", "ankle", "ankles", "anklet", "annoyed", "annoying", "anorexia", "anova", "ant", "antelope",
             "antibiotics", "antisocial behaviour", "ants", "anxiety", "anxious", "apartment", "apple", "apple tree",
             "apples", "approachable", "apricot", "april", "argon", "arm", "armchair", "armed robbery", "arms",
             "arrogant", "arsenic", "arson", "art", "art form", "article", "artistic movement", "ash", "asparagus",
             "assault", "astrology", "astronomy", "astrophysics", "atheism", "athletics", "attempted murder", "attic",
             "aubergine", "auburn", "august", "aunt", "auntie", "aunties", "autism", "autobiography", "autumn",
             "average", "avocado", "axe", "babysitter", "bacardi", "back", "bacon", "badger", "badminton", "baha'i",
             "baileys", "baker", "bamboo", "banana", "bananas", "banjo", "bar staff", "bark", "baron", "baroness",
             "barrister", "bartender", "baseball", "baseball bat", "baseball cap", "basement", "basil", "basketball",
             "bass", "bass guitar", "bassoon", "bat", "bath", "bath mat", "bathroom", "bathroom fixture", "bathtub",
             "battery", "beach", "beaches", "beagle", "beams", "bean sprouts", "beanie", "beans", "bear", "beard",
             "bed", "bedroom", "beds", "bedside table", "bedtime", "bee", "beef", "beer", "bees", "beetle", "beetles",
             "beetroot", "beige", "belt", "benzodiazepine", "beret", "beryllium", "best friend", "best friends",
             "bicycle", "bidet", "bike", "bike with stabilisers", "biochemistry", "biofuel", "biography", "biology",
             "biomedical", "bipolar", "bipolar disorder", "birch", "bird", "bird of prey", "birthday", "birthday party",
             "bison", "black", "blackberries", "blackberry", "blackbird", "blackcurrants", "blanket", "blankets",
             "blender", "blind", "blocks", "blog", "blonde", "blood", "blood orange", "blouse", "blue", "blue tit",
             "bluebell", "bluebells", "blueberries", "blueberry", "bluebird", "blush", "blusher", "boa constrictor",
             "boat", "boats", "bobble", "bobsledding", "bobsleigh", "body", "body of water", "bolts", "bomb", "bones",
             "bongos", "book", "book genre", "bookcase", "books", "boots", "border collie", "boron", "bottle opener",
             "bow", "bow and arrow", "bowl", "bowler", "box plot", "boxer", "boyfriend", "bra", "bracelet", "bracelets",
             "brain", "brain surgeon", "branch", "branches", "brandy", "brass", "brave", "brazil", "bread knife",
             "bread maker", "break", "breakfast", "breed of dog", "breezy", "brick", "bricks", "bright", "broccoli",
             "broken", "broken bone", "broken bones", "broken leg", "bromine", "bronze", "bronzer", "brother",
             "brother-in-law", "brown", "bruise", "bruises", "brunette", "brush", "brussels sprouts", "bubbly",
             "bubonic plague", "bucket", "buddhism", "buddhist", "budgie", "builder", "building", "building material",
             "bulimia", "bull", "bulldog", "bumblebee", "bungalow", "bungalows", "burglary", "burgundy", "burn", "bus",
             "bus driver", "bus station", "business", "business studies", "businessman", "butane", "butter",
             "buttercup", "butterfly", "butternut squash", "buzzard", "cabbage", "cabin", "cabinet", "cabinets",
             "caesium", "caffeine", "cajun", "calcium", "calf", "calm", "calpol", "calves", "camel",
             "camping equipment", "can opener", "canal", "canary", "cancer", "cannabis", "canoe", "canoeing", "cap",
             "captain", "car", "caravan", "carbon", "cardamom", "cardigan", "carer", "caring", "carp", "carpenter",
             "carpenter's tool", "carpet", "carrot", "carrots", "cars", "carving knife", "cashew", "cashews", "cashier",
             "cashmere", "castle", "cat", "caterpillar", "catfish", "cathedral", "catholic", "catholicism",
             "cauliflower", "cave", "caves", "cedar", "ceiling", "celery", "cello", "cement", "centilitre",
             "centimetre", "centimetres", "centipede", "centuries", "century", "ceo", "chainsaw", "chair", "chairs",
             "chalet", "champagne", "chao chao", "chapel", "cheek", "cheekbones", "cheeks", "cheerful", "cheerleading",
             "cheese", "cheetah", "cheetahs", "chef", "chemical element", "chemistry", "cherries", "cherry", "chest",
             "chest of drawers", "chestnut", "chi-square", "chicken", "chickenpox", "chickens", "chief", "chihuahua",
             "children's", "chilli", "chilli powder", "chin", "chinchilla", "chinos", "chisel", "chlamydia", "chlorine",
             "chocolate", "choker", "cholera", "chopping board", "christian", "christianity", "christmas",
             "christmas tree", "church", "cider", "cinema", "cinnamon", "circle", "citrus fruit", "clarinet", "cleaner",
             "clementine", "clementines", "clerk", "cliff", "clock", "cloth", "clothing", "cloudy", "clownfish", "club",
             "coach", "coal", "coat", "cobalt", "cobra", "cocaine", "cocker spaniel", "cockerpoo", "cockroach",
             "cockroaches", "cocktail", "cocodamol", "coconut", "cod", "codeine", "coffee table", "colander", "cold",
             "colleague", "colleagues", "colonel", "colour", "comedy", "commander", "common cold", "communism",
             "computer", "computer science", "concealer", "concrete", "concussion", "conditioner", "cone", "confidence",
             "confident", "conifer", "conservative", "conservatory", "consultant", "contemporary", "content", "contour",
             "copper", "coriander", "cormorant", "corn", "cornet", "corporal", "correlation", "corridor", "cosmetic",
             "cottage", "cotton", "couch", "cough", "coughing", "courgette", "cousin", "cousins", "cow", "cows",
             "cramps", "cream", "creative writing", "cricket", "crime", "criminology", "crocodile", "croquet",
             "cross-country skiing", "crossbow", "crow", "crowbar", "crows", "cruise", "cruise ship", "cube", "cubism",
             "cuboid", "cucumber", "cumin", "cupboard", "cups", "curling", "cut", "cuts", "cycling", "cylinder",
             "dachshund", "dad", "daffodil", "daffodils", "dagger", "dairy product", "daisy", "dalmatian", "dame",
             "dance", "dancer", "dancing", "dandelion", "dandelions", "darts", "data", "dates", "daughter", "dawn",
             "day", "day of the week", "days", "daytime", "decade", "decades", "decagon", "december", "deck",
             "deckchairs", "dedication", "deer", "defence lawyer", "dementia", "democracy", "democrat", "demon",
             "demons", "denim", "dentist", "depressed", "depression", "dermatologist", "desert", "desk", "desks",
             "despair", "detached", "determined", "devil", "diabetes", "diamond", "diarrhoea", "diary", "dictatorship",
             "diesel", "dill", "dinghy", "dining", "dining table", "dinner", "disappointment", "disease", "disgust",
             "disgusted", "dishwasher", "dismissive", "diving", "dizziness", "dizzy", "doctor", "doctor's",
             "dodecahedron", "dodge-ball", "dog", "dolphin", "domestic violence", "donkey", "door", "doors",
             "double bass", "doubles tennis", "dove", "dragon", "dragonfly", "drama", "drawers", "drawing", "dress",
             "dresses", "drill", "drinks", "driver", "drowsiness", "drug", "drumlin", "drums", "dry", "duchess", "duck",
             "ducks", "duke", "dune buggy", "dung beetle", "dungarees", "dusk", "eagle", "earring", "earrings", "ears",
             "earwig", "ebola", "economics", "ecstasy", "ecstatic", "eggs", "eighth", "elbow", "elbows",
             "electric guitar", "electricity", "elephant", "elephants", "elevators", "eleven", "elm", "embezzlement",
             "emerald", "emotion", "empathetic", "enemy", "engine", "engineer", "engineering", "english",
             "english bulldog", "english language", "english literature", "enthusiastic", "entrance", "envy", "epoch",
             "evening", "evening dress", "event", "evergreen", "excited", "excitement", "exit", "eye", "eyebrow pencil",
             "eyebrows", "eyelash", "eyelashes", "eyelid", "eyelids", "eyeliner", "eyes", "eyeshadow", "fabric", "face",
             "factory", "fake tan", "falcon", "fall", "family", "family relationship", "fantasy", "farm animal",
             "father", "father-in-law", "fear", "fearful", "february", "fedora", "feeling cold", "feet", "felt",
             "fencing", "fennel", "ferret", "ferry", "fever", "fiance", "fiction", "fifth", "fifty-one", "fifty-three",
             "figure skating", "file", "finger", "fingers", "fir", "fire", "firefighter", "fireman", "fireplace",
             "fish", "fishing boat", "fists", "five", "five eighths", "flamingo", "flat", "flat cap", "flats", "floor",
             "flower", "flowers", "flu", "fluoride", "flute", "fly", "flyer", "fog", "foggy", "food", "food processor",
             "foot", "football", "footstool", "forehead", "fork", "forks", "fortnight", "forty-one", "forty-seven",
             "forty-three", "foundation", "foundations", "four eighths", "four fifths", "four-by-four",
             "four-legged animal", "four-wheeled vehicle", "fox", "fraction", "fracture", "fractures", "frankenstein",
             "fraud", "freezer", "french", "french bulldog", "french horn", "friday", "fridge", "friend",
             "friendliness", "friendly", "friends", "friendship", "friendships", "frog", "front", "frosty", "fruit",
             "frustrated", "frustration", "frying pan", "fuel", "funeral", "funny", "fur", "furniture", "futon",
             "futsal", "gammon", "garage", "garam masala", "gardening tool", "garlic", "garnet", "gas", "gas stove",
             "gasoline", "gazelle", "gbh", "geese", "gemstone", "general", "general practice", "general practitioner",
             "generous", "genocide", "geography", "geology", "geometric shape", "gerbil", "german", "german shepherd",
             "ghost", "ghosts", "gilet", "gin", "ginger", "giraffe", "girlfriend", "glacier", "glaciers", "glass",
             "gloves", "go-kart", "goat", "goats", "god", "gold", "golden retriever", "goldfinch", "goldfish", "golf",
             "goose", "gooseberry", "gorilla", "gorillas", "gp", "gram", "grams", "granddad", "granddaughter",
             "grandfather", "grandma", "grandmother", "grandparents", "grandson", "grape", "grapefruit", "grapefruits",
             "grapes", "grass", "grasshopper", "graze", "great aunt", "great dane", "great grandfather",
             "great grandmother", "great grandparents", "great nephew", "great niece", "great tit", "great uncle",
             "greed", "green", "green beans", "green pepper", "green peppers", "green vegetable", "greenfly", "grey",
             "greyhound", "grief", "grievous bodily harm", "grill", "guava", "guinea pig", "guitar", "gun", "guns",
             "gurdwara", "gymnastics", "gynaecologist", "gynaecology", "h2o", "haddock", "hail", "hailstones", "hair",
             "hair colour", "hairdresser", "hairline", "hake", "half", "half brother", "half sister", "hallway", "ham",
             "hammer", "hamster", "hand", "handball", "hands", "happiness", "happy", "hard", "hardworking", "harmonica",
             "harp", "hat", "hate", "hatred", "hawk", "hazelnut", "hazelnuts", "head", "headache", "headaches",
             "healthcare assistant", "healthcare profession", "heart", "heavy goods vehicle", "hectagon",
             "hedge trimmer", "hedge trimmers", "hedgehog", "heels", "helicopter", "helium", "helpful", "heptagon",
             "herb", "heroin", "heron", "herring", "hexagon", "high temperature", "highlighter", "hiking",
             "hiking boots", "hill", "hills", "hindu", "hinduism", "hip", "hippo", "hips", "historical", "history",
             "hiv", "hob", "hockey", "hoe", "honest", "honesty", "hoodie", "hoodies", "hopelessness", "hornet",
             "horror", "horse", "horse chestnut", "horse riding", "horsefly", "hospital", "hot", "hotel", "hour",
             "hours", "house", "housefly", "houses", "hull", "human dwelling", "humid", "humility", "hummingbird",
             "humour", "hurricane", "husband", "husky", "hut", "hydrogen", "i.t.", "ibuprofen", "ice cream",
             "ice hockey", "ice skating", "icy", "igloo", "ignorant", "illegal", "impressionism", "inch", "inches",
             "inconsiderate", "independent", "indigo", "infectious disease", "injury", "insect", "insulation",
             "intelligence", "intelligent", "internet article", "intestines", "iodine", "iron", "irritable", "islam",
             "island", "isolation", "jack russell", "jackdaw", "jacket", "jager", "jagermeister", "jaguar", "jainism",
             "january", "javelin", "jaw", "jealous", "jealousy", "jeans", "jeep", "jellyfish", "jet", "jet-skiing",
             "jewellery", "joggers", "journal", "journal article", "journal articles", "journals", "joy", "joyful",
             "judaism", "judge", "judgemental", "judo", "july", "jumper", "june", "kale", "kangaroo", "karate", "kayak",
             "kayaking", "keel", "kerosene", "kettle", "keyboard", "kidnapping", "kilogram", "kilograms", "kilometre",
             "kilometres", "kind", "kindness", "king", "king charles spaniel", "kingfisher", "kitchen",
             "kitchen appliance", "kitchen utensil", "kite", "kiwi", "knee", "knees", "knickers", "knife", "knight",
             "knives", "koi carp", "korfball", "labradoodle", "labrador", "lacrosse", "ladle", "ladybird", "lager",
             "lake", "lakes", "lamb", "lamp", "lamps", "languages", "laughing", "laundry", "lavender", "law",
             "lawnmower", "lawyer", "lazy", "lead", "leaf", "leaflets", "leather", "leaves", "lecturer", "leek", "leg",
             "legal", "legal profession", "leggings", "legs", "lemon", "lemons", "lemur", "leopard", "lettuce",
             "leukemia", "librarian", "library", "lieutenant", "lifeboat", "light brown", "light year", "lightning",
             "lilac", "lilies", "lily", "lime", "linen", "linguistics", "lion", "lions", "lip gloss", "lip liner",
             "lips", "lipstick", "liqueur", "lithium", "litre", "littering", "liver", "living", "living room furniture",
             "lizard", "llama", "lobster", "loft", "loneliness", "lonely", "lord", "lorry", "loud", "lounge", "love",
             "loving", "loyal", "lsd", "luge", "lunchtime", "lungs", "lute", "lycra", "lying", "macadamia",
             "machine gun", "mackerel", "magazine", "magazines", "magenta", "magistrate", "magnesium", "magpie",
             "major", "makeup", "malaria", "malibu", "management", "manager", "mandarin", "mandarins", "mange tout",
             "mango", "manic depression", "mansion", "manslaughter", "maple", "maracas", "march", "margarine",
             "marijuana", "marketing", "maroon", "mascara", "mast", "matches", "mathematics", "maths", "may", "mdma",
             "mead", "mean", "measles", "meat", "media studies", "median", "medical assistant", "medical specialty",
             "medicine", "meerkat", "meeting", "melon", "meningitis", "mental abuse", "metal", "meth", "metre",
             "metres", "mice", "microgram", "micrometer", "microwave", "midday", "midnight", "midwife", "mile", "miles",
             "military title", "milk", "millennia", "millennium", "milligram", "milligrams", "millilitre",
             "millilitres", "millimetre", "millimetres", "millipede", "millisecond", "milliseconds", "minibus", "mint",
             "minute", "minutes", "mirror", "miserable", "mixed", "mixer", "mobile home", "mode", "modern art",
             "monarchy", "monastery", "monday", "monkey", "monsoon", "month", "months", "moody", "moped", "mormonism",
             "morning", "morphine", "mortar", "mosque", "mosquito", "moth", "mother", "mother-in-law", "motivated",
             "motorbike", "motorcycle", "mountain", "mountains", "mouse", "moustache", "mouth", "mugging", "mum",
             "mumps", "murder", "museum", "music", "musical instrument", "muslim", "mutton", "mystery", "nail",
             "nail varnish", "nails", "nanometre", "naproxen", "narcissistic", "natural landform", "nausea", "navy",
             "neck", "necklace", "nectarine", "negative emotion", "negative personal quality", "neon", "nephew",
             "nervous", "netball", "neurology", "neuroscience", "newspaper", "newspapers", "nice", "nickel", "nicotine",
             "niece", "night", "nighttime", "nine", "nineteen", "ninth", "nitrogen", "non-fiction", "non-judgemental",
             "non-violent crime", "nonagon", "noon", "nose", "nose ring", "nose rings", "nostrils", "noun", "novel",
             "november", "nurse", "nut", "nutmeg", "nylon", "oak", "oak tree", "oar", "oars", "oboe", "ocd", "ocean",
             "oceans", "octagon", "october", "office", "office building", "officer", "offices", "oil", "one",
             "one eighth", "one fifth", "one quarter", "one tenth", "onion", "onyx", "opal", "opium", "optician",
             "optimistic", "orange", "oranges", "orchid", "oregano", "organ", "organs", "orthodontist", "orthopaedic",
             "ostrich", "ounce", "ounces", "outgoing", "oven", "overcast", "overcoat", "overjoyed", "overwhelmed",
             "owl", "oxygen", "p-value", "paediatric", "paediatrician", "paediatrics", "paganism", "pain", "painting",
             "pamphlet", "pamphlets", "pan", "panda", "pans", "pants", "papaya", "paprika", "paracetamol", "paralegal",
             "parallelogram", "paramedic", "parent", "parrot", "parrotfish", "parsec", "parsley", "parsnip", "parsnips",
             "part of a boat", "part of a building", "part of a tree", "part of the body", "part of the face",
             "parties", "party", "passion", "patient", "pe", "peach", "peaches", "peanut", "peanuts", "pear", "pearl",
             "pears", "peas", "peers", "pegs", "pelican", "pelvis", "penguin", "penny farthing", "pentagon", "pepper",
             "peppers", "percentages", "percussion", "personal quality", "personality disorder", "pessimistic",
             "pesticides", "petrol", "petunia", "pharmacist", "philosophy", "physical education", "physics", "physio",
             "physiotherapist", "piano", "piccolo", "pictures", "pig", "pigeon", "pigs", "pillow", "pine", "pine tree",
             "pineapple", "pink", "pistachio", "pistachios", "pitbull", "plague", "plaice", "plane", "plaster",
             "plastic", "plastic surgery", "plate", "plates", "platinum", "playroom", "pliers", "plum", "plumber",
             "plums", "poetry", "polar bear", "poles", "police officer", "policeman", "polio", "polite", "political",
             "political system", "politician", "politics", "polo", "poltergeist", "polyester", "pomegranate", "pond",
             "poodle", "pool", "pop art", "poppy", "porch", "pork", "port", "portable stove", "positive",
             "positive emotion", "positive personal quality", "possession of drugs", "post office", "posters",
             "postmodernism", "potassium", "potato", "potatoes", "pots", "pottery", "pound", "pounds", "powder",
             "prawn", "prayer room", "prime number", "primer", "prince", "princess", "prism", "private", "probability",
             "profession", "professor", "pronoun", "propeller", "proportional representation", "protestant",
             "psychiatrist", "psychiatry", "psychological illness", "psychologist", "psychology", "psychosis", "pub",
             "puddle", "pufferfish", "puffin", "pug", "puma", "pumpkin", "pupils", "purple", "pyramid", "python",
             "quad bike", "quarter", "quartz", "queen", "queen mother", "quiet", "rabbit", "raccoon", "racket sport",
             "racquetball", "radiator", "radiographer", "radiologist", "radiology", "radish", "rain", "raining",
             "rainy", "raisin", "rake", "range", "rape", "rash", "rashes", "raspberries", "raspberry", "rat", "rats",
             "rattlesnake", "raven", "reading material", "realism", "reception", "receptionist", "recorder",
             "rectangle", "red", "red wine", "redness", "reindeer", "relationship", "reliable", "relieved", "religion",
             "religious building", "religious studies", "reservoir", "rhino", "rhododendron", "rhombus", "ribs",
             "rifle", "rigging", "ring", "rings", "river", "rivers", "robbery", "robin", "rock", "rocket", "rodent",
             "roll mat", "rolling pin", "romance", "romantic", "roof", "room in a house", "rooms", "root", "roots",
             "rose", "rosemary", "roses", "rottweiler", "rounders", "rowing", "royal title", "rubella", "ruby",
             "rudder", "rude", "rug", "rugby", "rugby league", "ruler", "rum", "running", "runny nose", "sad",
             "sadness", "sage", "sail", "sailing", "sails", "salmon", "salt", "samoyed", "sand", "santa hat", "sap",
             "sapphire", "sardine", "satin", "satsuma", "saturday", "sausage dog", "sausages", "saw", "saxophone",
             "scab", "scared", "scarf", "schizophrenia", "schnapps", "school", "sci-fi", "science", "science fiction",
             "scientist", "scientology", "scooter", "scorpion", "scorpions", "screwdriver", "screws", "script",
             "scuba diving", "sculpture", "sculptures", "sea", "seafood", "seagull", "season", "secateurs", "second",
             "second cousin", "second cousins", "seconds", "secretary", "segway", "selenium", "selfish", "selfishness",
             "selfless", "semi-detached", "senior", "septagon", "september", "sergeant", "sergeant major", "seven",
             "seven eighths", "seventeen", "seventh", "sex on the beach", "sexual assault", "shampoo", "shark",
             "shears", "shed", "sheep", "sheepdog", "shelves", "sherry", "shield", "shih-tzu", "ship", "shirt",
             "shivering", "shock", "shoes", "shooting", "shootings", "shop", "shop assistant", "shoplifting", "shops",
             "shorts", "shotgun", "shoulder", "shoulders", "shovel", "shower", "shower curtain", "shy", "sick",
             "sickness", "side table", "sieve", "significance", "significance level", "sikh", "sikhism", "silk",
             "silver", "silver birch", "singer", "singing", "sink", "sir", "sister", "sister-in-law", "sitar",
             "six eighths", "six sevenths", "sixth", "sixty-seven", "skateboard", "skeleton", "sketch", "ski jump",
             "ski jumping", "ski slalom", "skiing", "skin", "skirt", "skirts", "skort", "skyscraper", "skyscrapers",
             "sledging", "sleeping bag", "sleeping mat", "smallpox", "smiling", "smoothie maker", "snake", "snapback",
             "sneezing", "snooker", "snow", "snowboarding", "snowing", "snowstorm", "snowy", "social gathering",
             "social relationship", "socialism", "sociology", "socks", "sodium", "sofa", "soiree", "soldier",
             "solicitor", "sombrero", "son", "sore throat", "sour cream", "southern comfort", "spade", "spaniel",
             "spanish", "spanner", "sparrow", "spatula", "spear", "speech and language therapist", "speed", "speedboat",
             "speeding", "sphere", "spice", "spider", "spiders", "spinach", "spine", "spirit", "spirits", "spoon",
             "spoons", "sport", "sports science", "sportswear", "sprain", "sprains", "spring", "spring onions",
             "springer spaniel", "sprouts", "square", "squash", "squid", "squirrel", "st bernard", "stabbing",
             "staffie", "stairs", "stairway", "standard deviation", "standard error", "standoffish", "starboard",
             "starling", "statistical term", "statistics", "statue", "statues", "steak", "stealing", "steel", "stem",
             "step-parents", "stepbrother", "stepdad", "stepfather", "stepmother", "stepmum", "stepsister", "stern",
             "stick", "stinging insect", "stomach", "stomach ache", "stone", "stones", "stool", "stork", "storm",
             "stormy", "stove", "strain", "straw", "strawberries", "strawberry", "strawberry blonde", "stream",
             "stress", "stressed", "strimmer", "string instrument", "study", "stump", "suit", "sulphur", "summer",
             "sun", "sunday", "sunflower", "sunflowers", "sunny", "superheroes", "supernatural being", "surfing",
             "surgeon", "surgery", "surprise", "swamp", "swan", "swans", "sweater", "sweating", "sweatshirt", "swede",
             "sweet potato", "sweetcorn", "swelling", "swimming", "swimming costume", "swimming pool", "sword",
             "swordfish", "sycamore", "symptom of illness", "synagogue", "synchronised swimming", "t-shirt", "t-shirts",
             "t-test", "table", "table tennis", "tablespoon", "tangerine", "tank top", "taoism", "tap", "tape measure",
             "taser", "tax evasion", "taxi", "tb", "teacher", "teal", "team sport", "teaspoon", "teatime", "technician",
             "teepee", "teeth", "television", "temperate", "temperature", "temple", "tennis", "tent", "tent pegs",
             "tent poles", "tenth", "tequila", "terrace", "terrier", "textbook", "theatre", "theft", "therapist",
             "thigh", "thighs", "third", "third cousins", "thirteen", "thirty-one", "thirty-seven", "thoughtful",
             "three", "three eighths", "three quarters", "three-dimensional shape", "thrilled", "thriller", "thunder",
             "thunderstorm", "thursday", "thyme", "tie", "tiger", "tights", "tiles", "timber", "time of day", "tin",
             "tiredness", "titanium", "toaster", "toastie maker", "tobogganing", "toe", "toe rings", "toes", "toilet",
             "toilet roll holder", "tomato", "tomatoes", "ton", "tongs", "tongue", "tonsillitis", "tool", "top",
             "topaz", "torch", "torso", "torture", "toucan", "towel rail", "tower", "tractor", "train", "train station",
             "trainers", "trangia", "transcript", "trapezium", "tree", "triangle", "trombone", "trousers", "trout",
             "trowel", "truck", "trucks", "trumpet", "trunk", "trustworthy", "tuba", "tuesday", "tulip", "tuna",
             "turkey", "turmeric", "turnip", "turnips", "turquoise", "tv", "tv stand", "twelfth", "twenty-nine",
             "twenty-three", "twig", "twigs", "two", "two eighths", "two fifths", "two sevenths", "two sixths",
             "two thirds", "two-dimensional shape", "two-wheeled vehicle", "type of word", "typhoid", "ukulele",
             "uncle", "uncles", "understanding", "underwear", "unhappy", "unit of length", "unit of time",
             "unit of weight", "university", "unsupportive", "upset", "uranium", "valley", "valleys", "vampire",
             "vampires", "van", "vandalism", "variance", "vase", "vatican", "veal", "vegetable", "vehicle", "velvet",
             "venison", "verb", "verbal abuse", "vest", "viola", "violence", "violent crime", "violet", "violets",
             "violin", "viper", "vodka", "voice", "volcano", "volcanoes", "volleyball", "vomit", "vomiting", "vulture",
             "wagon", "waist", "waiter", "waitress", "wakeboarding", "wall", "walls", "walnut", "walnuts", "wardrobe",
             "wardrobes", "warm", "washing machine", "washroom", "wasp", "watch", "watches", "water", "water bird",
             "water polo", "water skiing", "water sport", "watermelon", "waterproofs", "waterskiing", "weapon",
             "weather", "website", "websites", "wedding", "weddings", "wednesday", "weed", "week", "weeks",
             "weighing scales", "werewolf", "westie", "wet", "whale", "whales", "wheel", "whipped cream", "whisk",
             "whiskey", "white", "white wine", "white-water rafting", "wife", "willow", "willow tree", "wind",
             "wind instrument", "window", "windows", "windpipe", "windsurfing", "windy", "wine", "winter",
             "winter sport", "witches", "wolf", "wood", "wooden spoon", "wooden spoons", "woodlouse", "woodpecker",
             "wool", "woolly", "worm", "worried", "wound", "wrench", "writer", "xylophone", "yacht", "yard", "yards",
             "year", "years", "yellow", "yoghurt", "yorkshire terrier", "young adult", "zebra", "zinc", "zombie",
             "zombies"]
        )

    def test_single_word_vocabulary(self):
        cp = CategoryProduction(word_tokenise=None)
        self.assertListEqual(
            cp.single_word_vocabulary,
            ["1pm", "2pm", "3pm", "4pm", "57", "abrupt", "absinthe", "abstract", "abuse", "academic", "accounting",
             "ache", "aching", "acorn", "acquaintance", "acquaintances", "action", "actor", "actress", "adder", "adhd",
             "adjective", "adult", "adventure", "adverb", "aeroplane", "afraid", "afternoon", "aggressive", "aids",
             "air", "alcohol", "alcoholic", "algebra", "alien", "almond", "almonds", "aluminium", "amber", "ambulance",
             "american", "amethyst", "anaconda", "anchor", "angel", "angelfish", "anger", "angry", "animal",
             "ankle", "ankles", "anklet", "annoyed", "annoying", "anorexia", "anova", "ant", "antelope", "antibiotics",
             "antisocial", "ants", "anxiety", "anxious", "apartment", "apple", "apples", "appliance", "approachable",
             "apricot", "april", "argon", "arm", "armchair", "armed", "arms", "arrogant", "arrow", "arsenic", "arson",
             "art", "article", "articles", "artistic", "ash", "asparagus", "assault", "assistant", "astrology",
             "astronomy", "astrophysics", "atheism", "athletics", "attempted", "attic", "aubergine", "auburn", "august",
             "aunt", "auntie", "aunties", "autism", "autobiography", "autumn", "average", "avocado", "axe",
             "babysitter", "bacardi", "back", "bacon", "badger", "badminton", "bag", "baha'i", "baileys", "baker",
             "bamboo", "banana", "bananas", "banjo", "bar", "bark", "baron", "baroness", "barrister", "bartender",
             "baseball", "basement", "basil", "basketball", "bass", "bassoon", "bat", "bath", "bathroom", "bathtub",
             "battery", "beach", "beaches", "beagle", "beams", "bean", "beanie", "beans", "bear", "beard", "bed",
             "bedroom", "beds", "bedside", "bedtime", "bee", "beef", "beer", "bees", "beetle", "beetles", "beetroot",
             "behaviour", "beige", "being", "belt", "benzodiazepine", "beret", "bernard", "beryllium", "best",
             "bicycle", "bidet", "bike", "biochemistry", "biofuel", "biography", "biology", "biomedical", "bipolar",
             "birch", "bird", "birthday", "bison", "black", "blackberries", "blackberry", "blackbird", "blackcurrants",
             "blanket", "blankets", "blender", "blind", "blocks", "blog", "blonde", "blood", "blouse", "blue",
             "bluebell", "bluebells", "blueberries", "blueberry", "bluebird", "blush", "blusher", "boa", "board",
             "boat", "boats", "bobble", "bobsledding", "bobsleigh", "bodily", "body", "bolts", "bomb", "bone", "bones",
             "bongos", "book", "bookcase", "books", "boots", "border", "boron", "bottle", "bow", "bowl", "bowler",
             "box", "boxer", "boyfriend", "bra", "bracelet", "bracelets", "brain", "branch", "branches", "brandy",
             "brass", "brave", "brazil", "bread", "break", "breakfast", "breed", "breezy", "brick", "bricks", "bright",
             "broccoli", "broken", "bromine", "bronze", "bronzer", "brother", "brother-in-law", "brown", "bruise",
             "bruises", "brunette", "brush", "brussels", "bubbly", "bubonic", "bucket", "buddhism", "buddhist",
             "budgie", "buggy", "builder", "building", "bulimia", "bull", "bulldog", "bumblebee", "bungalow",
             "bungalows", "burglary", "burgundy", "burn", "bus", "business", "businessman", "butane", "butter",
             "buttercup", "butterfly", "butternut", "buzzard", "cabbage", "cabin", "cabinet", "cabinets", "caesium",
             "caffeine", "cajun", "calcium", "calf", "calm", "calpol", "calves", "camel", "camping", "can", "canal",
             "canary", "cancer", "cannabis", "canoe", "canoeing", "cap", "captain", "car", "caravan", "carbon",
             "cardamom", "cardigan", "carer", "caring", "carp", "carpenter", "carpenter's", "carpet", "carrot",
             "carrots", "cars", "carving", "cashew", "cashews", "cashier", "cashmere", "castle", "cat", "caterpillar",
             "catfish", "cathedral", "catholic", "catholicism", "cauliflower", "cave", "caves", "cedar", "ceiling",
             "celery", "cello", "cement", "centilitre", "centimetre", "centimetres", "centipede", "centuries",
             "century", "ceo", "chainsaw", "chair", "chairs", "chalet", "champagne", "chao", "chapel", "charles",
             "cheek", "cheekbones", "cheeks", "cheerful", "cheerleading", "cheese", "cheetah", "cheetahs", "chef",
             "chemical", "chemistry", "cherries", "cherry", "chest", "chestnut", "chi-square", "chicken", "chickenpox",
             "chickens", "chief", "chihuahua", "children's", "chilli", "chin", "chinchilla", "chinos", "chisel",
             "chlamydia", "chlorine", "chocolate", "choker", "cholera", "chopping", "christian", "christianity",
             "christmas", "church", "cider", "cinema", "cinnamon", "circle", "citrus", "clarinet", "cleaner",
             "clementine", "clementines", "clerk", "cliff", "clock", "cloth", "clothing", "cloudy", "clownfish", "club",
             "coach", "coal", "coat", "cobalt", "cobra", "cocaine", "cocker", "cockerpoo", "cockroach", "cockroaches",
             "cocktail", "cocodamol", "coconut", "cod", "codeine", "coffee", "colander", "cold", "colleague",
             "colleagues", "collie", "colonel", "colour", "comedy", "comfort", "commander", "common", "communism",
             "computer", "concealer", "concrete", "concussion", "conditioner", "cone", "confidence", "confident",
             "conifer", "conservative", "conservatory", "constrictor", "consultant", "contemporary", "content",
             "contour", "copper", "coriander", "cormorant", "corn", "cornet", "corporal", "correlation", "corridor",
             "cosmetic", "costume", "cottage", "cotton", "couch", "cough", "coughing", "courgette", "cousin", "cousins",
             "cow", "cows", "cramps", "cream", "creative", "cricket", "crime", "criminology", "crocodile", "croquet",
             "cross-country", "crossbow", "crow", "crowbar", "crows", "cruise", "cube", "cubism", "cuboid", "cucumber",
             "cumin", "cupboard", "cups", "curling", "curtain", "cut", "cuts", "cycling", "cylinder", "dachshund",
             "dad", "daffodil", "daffodils", "dagger", "dairy", "daisy", "dalmatian", "dame", "dance", "dancer",
             "dancing", "dandelion", "dandelions", "dane", "darts", "data", "dates", "daughter", "dawn", "day", "days",
             "daytime", "decade", "decades", "decagon", "december", "deck", "deckchairs", "dedication", "deer",
             "defence", "dementia", "democracy", "democrat", "demon", "demons", "denim", "dentist", "depressed",
             "depression", "dermatologist", "desert", "desk", "desks", "despair", "detached", "determined", "deviation",
             "devil", "diabetes", "diamond", "diarrhoea", "diary", "dictatorship", "diesel", "dill", "dinghy", "dining",
             "dinner", "disappointment", "disease", "disgust", "disgusted", "dishwasher", "dismissive", "disorder",
             "diving", "dizziness", "dizzy", "doctor", "doctor's", "dodecahedron", "dodge-ball", "dog", "dolphin",
             "domestic", "donkey", "door", "doors", "double", "doubles", "dove", "dragon", "dragonfly", "drama",
             "drawers", "drawing", "dress", "dresses", "drill", "drink", "drinks", "driver", "drowsiness", "drug",
             "drugs", "drumlin", "drums", "dry", "duchess", "duck", "ducks", "duke", "dune", "dung", "dungarees",
             "dusk", "dwelling", "eagle", "earring", "earrings", "ears", "earwig", "ebola", "economics", "ecstasy",
             "ecstatic", "education", "eggs", "eighth", "eighths", "elbow", "elbows", "electric", "electricity",
             "element", "elephant", "elephants", "elevators", "eleven", "elm", "embezzlement", "emerald", "emotion",
             "empathetic", "enemy", "engine", "engineer", "engineering", "english", "enthusiastic", "entrance", "envy",
             "epoch", "equipment", "error", "evasion", "evening", "event", "evergreen", "excited", "excitement", "exit",
             "eye", "eyebrow", "eyebrows", "eyelash", "eyelashes", "eyelid", "eyelids", "eyeliner", "eyes", "eyeshadow",
             "fabric", "face", "factory", "fake", "falcon", "fall", "family", "fantasy", "farm", "farthing", "father",
             "father-in-law", "fear", "fearful", "february", "fedora", "feeling", "feet", "felt", "fencing", "fennel",
             "ferret", "ferry", "fever", "fiance", "fiction", "fifth", "fifths", "fifty-one", "fifty-three", "figure",
             "file", "finger", "fingers", "fir", "fire", "firefighter", "fireman", "fireplace", "fish", "fishing",
             "fists", "five", "fixture", "flamingo", "flat", "flats", "floor", "flower", "flowers", "flu", "fluoride",
             "flute", "fly", "flyer", "fog", "foggy", "food", "foot", "football", "footstool", "forehead", "fork",
             "forks", "form", "fortnight", "forty-one", "forty-seven", "forty-three", "foundation", "foundations",
             "four", "four-by-four", "four-legged", "four-wheeled", "fox", "fraction", "fracture", "fractures",
             "frankenstein", "fraud", "freezer", "french", "friday", "fridge", "friend", "friendliness", "friendly",
             "friends", "friendship", "friendships", "frog", "front", "frosty", "fruit", "frustrated", "frustration",
             "frying", "fuel", "funeral", "funny", "fur", "furniture", "futon", "futsal", "gammon", "garage", "garam",
             "gardening", "garlic", "garnet", "gas", "gasoline", "gathering", "gazelle", "gbh", "geese", "gemstone",
             "general", "generous", "genocide", "genre", "geography", "geology", "geometric", "gerbil", "german",
             "ghost", "ghosts", "gilet", "gin", "ginger", "giraffe", "girlfriend", "glacier", "glaciers", "glass",
             "gloss", "gloves", "go-kart", "goat", "goats", "god", "gold", "golden", "goldfinch", "goldfish", "golf",
             "goods", "goose", "gooseberry", "gorilla", "gorillas", "gp", "gram", "grams", "granddad", "granddaughter",
             "grandfather", "grandma", "grandmother", "grandparents", "grandson", "grape", "grapefruit", "grapefruits",
             "grapes", "grass", "grasshopper", "graze", "great", "greed", "green", "greenfly", "grey", "greyhound",
             "grief", "grievous", "grill", "guava", "guinea", "guitar", "gun", "guns", "gurdwara", "gymnastics",
             "gynaecologist", "gynaecology", "h2o", "haddock", "hail", "hailstones", "hair", "hairdresser", "hairline",
             "hake", "half", "hallway", "ham", "hammer", "hamster", "hand", "handball", "hands", "happiness", "happy",
             "hard", "hardworking", "harm", "harmonica", "harp", "hat", "hate", "hatred", "hawk", "hazelnut",
             "hazelnuts", "head", "headache", "headaches", "healthcare", "heart", "heavy", "hectagon", "hedge",
             "hedgehog", "heels", "helicopter", "helium", "helpful", "heptagon", "herb", "heroin", "heron", "herring",
             "hexagon", "high", "highlighter", "hiking", "hill", "hills", "hindu", "hinduism", "hip", "hippo", "hips",
             "historical", "history", "hiv", "hob", "hockey", "hoe", "holder", "home", "honest", "honesty", "hoodie",
             "hoodies", "hopelessness", "horn", "hornet", "horror", "horse", "horsefly", "hospital", "hot", "hotel",
             "hour", "hours", "house", "housefly", "houses", "hull", "human", "humid", "humility", "hummingbird",
             "humour", "hurricane", "husband", "husky", "hut", "hydrogen", "i.t.", "ibuprofen", "ice", "icy", "igloo",
             "ignorant", "illegal", "illness", "impressionism", "in", "inch", "inches", "inconsiderate", "independent",
             "indigo", "infectious", "injury", "insect", "instrument", "insulation", "intelligence", "intelligent",
             "internet", "intestines", "iodine", "iron", "irritable", "islam", "island", "isolation", "jack", "jackdaw",
             "jacket", "jager", "jagermeister", "jaguar", "jainism", "january", "javelin", "jaw", "jealous", "jealousy",
             "jeans", "jeep", "jellyfish", "jet", "jet-skiing", "jewellery", "joggers", "journal", "journals", "joy",
             "joyful", "judaism", "judge", "judgemental", "judo", "july", "jump", "jumper", "jumping", "june", "kale",
             "kangaroo", "karate", "kayak", "kayaking", "keel", "kerosene", "kettle", "keyboard", "kidnapping",
             "kilogram", "kilograms", "kilometre", "kilometres", "kind", "kindness", "king", "kingfisher", "kitchen",
             "kite", "kiwi", "knee", "knees", "knickers", "knife", "knight", "knives", "koi", "korfball", "labradoodle",
             "labrador", "lacrosse", "ladle", "ladybird", "lager", "lake", "lakes", "lamb", "lamp", "lamps", "landform",
             "language", "languages", "laughing", "laundry", "lavender", "law", "lawnmower", "lawyer", "lazy", "lead",
             "leaf", "leaflets", "league", "leather", "leaves", "lecturer", "leek", "leg", "legal", "leggings", "legs",
             "lemon", "lemons", "lemur", "length", "leopard", "lettuce", "leukemia", "level", "librarian", "library",
             "lieutenant", "lifeboat", "light", "lightning", "lilac", "lilies", "lily", "lime", "linen", "liner",
             "linguistics", "lion", "lions", "lip", "lips", "lipstick", "liqueur", "literature", "lithium", "litre",
             "littering", "liver", "living", "lizard", "llama", "lobster", "loft", "loneliness", "lonely", "lord",
             "lorry", "loud", "lounge", "love", "loving", "loyal", "lsd", "luge", "lunchtime", "lungs", "lute", "lycra",
             "lying", "macadamia", "machine", "mackerel", "magazine", "magazines", "magenta", "magistrate", "magnesium",
             "magpie", "major", "maker", "makeup", "malaria", "malibu", "management", "manager", "mandarin",
             "mandarins", "mange", "mango", "manic", "mansion", "manslaughter", "maple", "maracas", "march",
             "margarine", "marijuana", "marketing", "maroon", "masala", "mascara", "mast", "mat", "matches", "material",
             "mathematics", "maths", "may", "mdma", "mead", "mean", "measles", "measure", "meat", "media", "median",
             "medical", "medicine", "meerkat", "meeting", "melon", "meningitis", "mental", "metal", "meth", "metre",
             "metres", "mice", "microgram", "micrometer", "microwave", "midday", "midnight", "midwife", "mile", "miles",
             "military", "milk", "millennia", "millennium", "milligram", "milligrams", "millilitre", "millilitres",
             "millimetre", "millimetres", "millipede", "millisecond", "milliseconds", "minibus", "mint", "minute",
             "minutes", "mirror", "miserable", "mixed", "mixer", "mobile", "mode", "modern", "monarchy", "monastery",
             "monday", "monkey", "monsoon", "month", "months", "moody", "moped", "mormonism", "morning", "morphine",
             "mortar", "mosque", "mosquito", "moth", "mother", "mother-in-law", "motivated", "motorbike", "motorcycle",
             "mountain", "mountains", "mouse", "moustache", "mouth", "movement", "mugging", "mum", "mumps", "murder",
             "museum", "music", "musical", "muslim", "mutton", "mystery", "nail", "nails", "nanometre", "naproxen",
             "narcissistic", "natural", "nausea", "navy", "neck", "necklace", "nectarine", "negative", "neon", "nephew",
             "nervous", "netball", "neurology", "neuroscience", "newspaper", "newspapers", "nice", "nickel", "nicotine",
             "niece", "night", "nighttime", "nine", "nineteen", "ninth", "nitrogen", "non-fiction", "non-judgemental",
             "non-violent", "nonagon", "noon", "nose", "nostrils", "noun", "novel", "november", "number", "nurse",
             "nut", "nutmeg", "nylon", "oak", "oar", "oars", "oboe", "ocd", "ocean", "oceans", "octagon", "october",
             "office", "officer", "offices", "oil", "on", "one", "onion", "onions", "onyx", "opal", "opener",
             "opium", "optician", "optimistic", "orange", "oranges", "orchid", "oregano", "organ", "organs",
             "orthodontist", "orthopaedic", "ostrich", "ounce", "ounces", "outgoing", "oven", "overcast", "overcoat",
             "overjoyed", "overwhelmed", "owl", "oxygen", "p-value", "paediatric", "paediatrician", "paediatrics",
             "paganism", "pain", "painting", "pamphlet", "pamphlets", "pan", "panda", "pans", "pants", "papaya",
             "paprika", "paracetamol", "paralegal", "parallelogram", "paramedic", "parent", "parrot", "parrotfish",
             "parsec", "parsley", "parsnip", "parsnips", "part", "parties", "party", "passion", "patient", "pe",
             "peach", "peaches", "peanut", "peanuts", "pear", "pearl", "pears", "peas", "peers", "pegs", "pelican",
             "pelvis", "pencil", "penguin", "penny", "pentagon", "pepper", "peppers", "percentages", "percussion",
             "personal", "personality", "pessimistic", "pesticides", "petrol", "petunia", "pharmacist", "philosophy",
             "physical", "physics", "physio", "physiotherapist", "piano", "piccolo", "pictures", "pig", "pigeon",
             "pigs", "pillow", "pin", "pine", "pineapple", "pink", "pistachio", "pistachios", "pitbull", "plague",
             "plaice", "plane", "plaster", "plastic", "plate", "plates", "platinum", "playroom", "pliers", "plot",
             "plum", "plumber", "plums", "poetry", "polar", "poles", "police", "policeman", "polio", "polite",
             "political", "politician", "politics", "polo", "poltergeist", "polyester", "pomegranate", "pond", "poodle",
             "pool", "pop", "poppy", "porch", "pork", "port", "portable", "positive", "possession", "post", "posters",
             "postmodernism", "potassium", "potato", "potatoes", "pots", "pottery", "pound", "pounds", "powder",
             "practice", "practitioner", "prawn", "prayer", "prey", "prime", "primer", "prince", "princess", "prism",
             "private", "probability", "processor", "product", "profession", "professor", "pronoun", "propeller",
             "proportional", "protestant", "psychiatrist", "psychiatry", "psychological", "psychologist", "psychology",
             "psychosis", "pub", "puddle", "pufferfish", "puffin", "pug", "puma", "pumpkin", "pupils", "purple",
             "pyramid", "python", "quad", "quality", "quarter", "quarters", "quartz", "queen", "quiet", "rabbit",
             "raccoon", "racket", "racquetball", "radiator", "radiographer", "radiologist", "radiology", "radish",
             "rafting", "rail", "rain", "raining", "rainy", "raisin", "rake", "range", "rape", "rash", "rashes",
             "raspberries", "raspberry", "rat", "rats", "rattlesnake", "raven", "reading", "realism", "reception",
             "receptionist", "recorder", "rectangle", "red", "redness", "reindeer", "relationship", "reliable",
             "relieved", "religion", "religious", "representation", "reservoir", "retriever", "rhino", "rhododendron",
             "rhombus", "ribs", "riding", "rifle", "rigging", "ring", "rings", "river", "rivers", "robbery", "robin",
             "rock", "rocket", "rodent", "roll", "rolling", "romance", "romantic", "roof", "room", "rooms", "root",
             "roots", "rose", "rosemary", "roses", "rottweiler", "rounders", "rowing", "royal", "rubella", "ruby",
             "rudder", "rude", "rug", "rugby", "ruler", "rum", "running", "runny", "russell", "sad", "sadness", "sage",
             "sail", "sailing", "sails", "salmon", "salt", "samoyed", "sand", "santa", "sap", "sapphire", "sardine",
             "satin", "satsuma", "saturday", "sausage", "sausages", "saw", "saxophone", "scab", "scales", "scared",
             "scarf", "schizophrenia", "schnapps", "school", "sci-fi", "science", "scientist", "scientology", "scooter",
             "scorpion", "scorpions", "screwdriver", "screws", "script", "scuba", "sculpture", "sculptures", "sea",
             "seafood", "seagull", "season", "secateurs", "second", "seconds", "secretary", "segway", "selenium",
             "selfish", "selfishness", "selfless", "semi-detached", "senior", "septagon", "september", "sergeant",
             "seven", "seventeen", "seventh", "sevenths", "sex", "sexual", "shampoo", "shape", "shark", "shears",
             "shed", "sheep", "sheepdog", "shelves", "shepherd", "sherry", "shield", "shih-tzu", "ship", "shirt",
             "shivering", "shock", "shoes", "shooting", "shootings", "shop", "shoplifting", "shops", "shorts",
             "shotgun", "shoulder", "shoulders", "shovel", "shower", "shy", "sick", "sickness", "side", "sieve",
             "significance", "sikh", "sikhism", "silk", "silver", "singer", "singing", "sink", "sir", "sister",
             "sister-in-law", "sitar", "six", "sixth", "sixths", "sixty-seven", "skateboard", "skating", "skeleton",
             "sketch", "ski", "skiing", "skin", "skirt", "skirts", "skort", "skyscraper", "skyscrapers", "slalom",
             "sledging", "sleeping", "smallpox", "smiling", "smoothie", "snake", "snapback", "sneezing", "snooker",
             "snow", "snowboarding", "snowing", "snowstorm", "snowy", "social", "socialism", "sociology", "socks",
             "sodium", "sofa", "soiree", "soldier", "solicitor", "sombrero", "son", "sore", "sour", "southern", "spade",
             "spaniel", "spanish", "spanner", "sparrow", "spatula", "spear", "specialty", "speech", "speed",
             "speedboat", "speeding", "sphere", "spice", "spider", "spiders", "spinach", "spine", "spirit", "spirits",
             "spoon", "spoons", "sport", "sports", "sportswear", "sprain", "sprains", "spring", "springer", "sprouts",
             "square", "squash", "squid", "squirrel", "st", "stabbing", "stabilisers", "staff", "staffie", "stairs",
             "stairway", "stand", "standard", "standoffish", "starboard", "starling", "station", "statistical",
             "statistics", "statue", "statues", "steak", "stealing", "steel", "stem", "step-parents", "stepbrother",
             "stepdad", "stepfather", "stepmother", "stepmum", "stepsister", "stern", "stick", "stinging", "stomach",
             "stone", "stones", "stool", "stork", "storm", "stormy", "stove", "strain", "straw", "strawberries",
             "strawberry", "stream", "stress", "stressed", "strimmer", "string", "studies", "study", "stump", "subject",
             "suit", "sulphur", "summer", "sun", "sunday", "sunflower", "sunflowers", "sunny", "superheroes",
             "supernatural", "surfing", "surgeon", "surgery", "surprise", "swamp", "swan", "swans", "sweater",
             "sweating", "sweatshirt", "swede", "sweet", "sweetcorn", "swelling", "swimming", "sword", "swordfish",
             "sycamore", "symptom", "synagogue", "synchronised", "system", "t-shirt", "t-shirts", "t-test", "table",
             "tablespoon", "tan", "tangerine", "tank", "taoism", "tap", "tape", "taser", "tax", "taxi", "tb", "teacher",
             "teal", "team", "teaspoon", "teatime", "technician", "teepee", "teeth", "television", "temperate",
             "temperature", "temple", "tennis", "tent", "tenth", "tequila", "term", "terrace", "terrier", "textbook",
             "theatre", "theft", "therapist", "thigh", "thighs", "third", "thirds", "thirteen", "thirty-one",
             "thirty-seven", "thoughtful", "three", "three-dimensional", "thrilled", "thriller", "throat", "thunder",
             "thunderstorm", "thursday", "thyme", "tie", "tiger", "tights", "tiles", "timber", "time", "tin",
             "tiredness", "tit", "titanium", "title", "toaster", "toastie", "tobogganing", "toe", "toes", "toilet",
             "tomato", "tomatoes", "ton", "tongs", "tongue", "tonsillitis", "tool", "top", "topaz", "torch", "torso",
             "torture", "toucan", "tout", "towel", "tower", "tractor", "train", "trainers", "trangia", "transcript",
             "trapezium", "tree", "triangle", "trimmer", "trimmers", "trombone", "trousers", "trout", "trowel", "truck",
             "trucks", "trumpet", "trunk", "trustworthy", "tuba", "tuesday", "tulip", "tuna", "turkey", "turmeric",
             "turnip", "turnips", "turquoise", "tv", "twelfth", "twenty-nine", "twenty-three", "twig", "twigs", "two",
             "two-dimensional", "two-wheeled", "type", "typhoid", "ukulele", "uncle", "uncles", "understanding",
             "underwear", "unhappy", "unit", "university", "unsupportive", "upset", "uranium", "utensil", "valley",
             "valleys", "vampire", "vampires", "van", "vandalism", "variance", "varnish", "vase", "vatican", "veal",
             "vegetable", "vehicle", "velvet", "venison", "verb", "verbal", "vest", "viola", "violence", "violent",
             "violet", "violets", "violin", "viper", "vodka", "voice", "volcano", "volcanoes", "volleyball", "vomit",
             "vomiting", "vulture", "wagon", "waist", "waiter", "waitress", "wakeboarding", "wall", "walls", "walnut",
             "walnuts", "wardrobe", "wardrobes", "warm", "washing", "washroom", "wasp", "watch", "watches", "water",
             "watermelon", "waterproofs", "waterskiing", "weapon", "weather", "website", "websites", "wedding",
             "weddings", "wednesday", "weed", "week", "weeks", "weighing", "weight", "werewolf", "westie", "wet",
             "whale", "whales", "wheel", "whipped", "whisk", "whiskey", "white", "white-water", "wife", "willow",
             "wind", "window", "windows", "windpipe", "windsurfing", "windy", "wine", "winter", "witches", "with",
             "wolf", "wood", "wooden", "woodlouse", "woodpecker", "wool", "woolly", "word", "worm", "worried", "wound",
             "wrench", "writer", "writing", "xylophone", "yacht", "yard", "yards", "year", "years", "yellow", "yoghurt",
             "yorkshire", "young", "zebra", "zinc", "zombie", "zombies"]
        )
